on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 1

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: src/scss/main.scss
          destination: css/main.css

      - name: Compile HTML from PUG files
        run: |
          npm i -g pug-cli
          if [ -d src ]; then
            find src/*.pug -type f -maxdepth 1 | xargs -I {} pug -P -b src --out . {}
          fi
          if [ -d src/articles ]; then
            find src/articles/* -type f -name "*.pug" -mindepth 2 -maxdepth 2 | xargs -I {} sh -c 'SRC="{}"; DEST="$(dirname "${SRC#src/}")/$(basename "${SRC}" .pug).html"; mkdir -p $(dirname ${DEST}) && cat "${SRC}" | pug -P -b src > "${DEST}"'
          fi
      - name: Add and commit changes to main branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add css/* articles/* *.html > /dev/null 2>&1 || true
          if ! git diff --cached --quiet; then
            git commit -m 'Update compiled files'
            git push
          else
            echo "No changes to commit."
          fi
